version: 2.1

jobs:
  build_and_test_inside_venv:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      # Download and cache dependencies 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  build_test_push_deploy:
    jobs:
      - build_and_test_inside_venv
